name: particle_swarm_optimization
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  csv: ^6.0.0
  excel: ^4.0.6
  navigation:
      git:
        url: https://github.com/chungweichung/navigation-tool.git
        ref: main
  vector_math: ^2.1.4
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
